### ISSUE TITLE
Generic entry point "{before/after}.save" "{before/after}.load"

### ISSUE THREAD

**Issue by ArThoX** [matb33/meteor-collection-hooks#189] opened 2016-07-05 18:18 UTC
Hi
Question: would it be possible to have generic entry point to save and load ?

For instance I want to do some post processing, whatever I insert/updated/upsert.

Or do you consider it's useless, and I just bind all what I need even if that's redundant ?

Regards

**Comment by ArThoX** [comment] 2016-07-05 18:24
Potentially rejected as duplicate of https://github.com/matb33/meteor-collection-hooks/issues/52

**Comment by ArThoX** [comment] 2016-07-05 18:38
Also I didnt know that

`Note that calling upsert will always fire .before.upsert hooks, but will call either .after.insert or .after.update hooks depending on the outcome of the upsert operation.`

So I guess it's only two lines...

**Comment by matb33** [comment] 2016-07-15 17:31
Will close as duplicate of #52

**Closed by matb33** 2016-07-15 17:31 UTC
