### ISSUE TITLE
Problem with custom "_id" in "before.insert()".

### ISSUE THREAD

**Issue by thearabbit** [matb33/meteor-collection-hooks#173] opened 2016-01-16 12:12 UTC
Problem with custom "_id" in "before.insert()".
```js
// fixture
var locatData = {........}; // don't have _id field
var locatId = Location.insert(locatData);
console.log('id after insert: ' + locatId);

// hook
Location.before.insert(function (userId, doc) {
    doc._id = '0001';
});

// Result
id after insert: random id
// It should be '0001'
```
Please help me.

**Comment by matb33** [comment] 2016-07-05 20:13
Duplicate of https://github.com/matb33/meteor-collection-hooks/issues/159

**Closed by matb33** 2016-07-05 20:13 UTC
