### ISSUE TITLE
How do we apply a hook to all collections?

### ISSUE THREAD

**Issue by trusktr** [matb33/meteor-collection-hooks#170] opened 2015-12-08 08:52 UTC
Is it `CollectionHooks.before.<hookName>(function() {...})`?

**Comment by crapthings** [comment] 2016-01-22 01:30
+1 how to do it ?

    _.each([Meteor.users, Products, Posts, Items], function(collection) {
        collection.before.insert();
    });

**Comment by trusktr** [comment] 2016-01-25 23:27
@crapthings That definitely works. I also just looked and see this: https://github.com/matb33/meteor-collection-hooks/blob/master/collection-hooks.js#L10-L15

Looks like we can put stuff in the defaults property there.

**Comment by trusktr** [comment] 2016-05-26 23:57
@matb33 ?

**Comment by bilics** [comment] 2016-06-09 17:20
+1 - How can I do this ?

**Comment by matb33** [comment] 2016-07-05 20:09
Agreed this would be useful

**Comment by matb33** [comment] 2016-07-05 20:14
Duplicate of https://github.com/matb33/meteor-collection-hooks/issues/110

**Closed by matb33** 2016-07-05 20:14 UTC
