### ISSUE TITLE
If multiple hooks are defined with the same type on the same collection, which of them gets run first, and which second...

### ISSUE THREAD

**Issue by dongzhi-yang** [matb33/meteor-collection-hooks#210] opened 2017-01-14 22:53 UTC
Hi, 
Suppose I have 5 different after.insert hooks defined on the same collection. In what order will they run? Is there a way I can controller this?

Thanks

**Comment by namirsab** [comment] 2017-01-15 22:43
They are gonna be run in the same order they get loaded.
You can control the order controlling the loading order of the files that declarethem, or controlling the loading order of the packages they are part of.

If you have all of them in the same file, they will be run  in the order you declare them in that file.

Anyway, if you are writing hooks that are affecting each other, you should maybe reconsider that. Hooks should be independent and if possible. If you want a hook to run after the other want, maybe you should just put them together in the same function :smile

I hope that helps. 

I close this issue because i think the problem is solved :smile:

**Closed by namirsab** 2017-01-15 22:43 UTC

**Comment by dongzhi-yang** [comment] 2017-01-16 02:27
Awesome, thanks for the detailed answer!


On Mon, Jan 16, 2017 at 6:43am, Namir < notifications@github.com [notifications@github.com] > wrote:
They are gonna be run in the same order they get loaded.
You can control the order controlling the loading order of the files that declarethem, or controlling the loading order of the packages they are part of.

If you have all of them in the same file, they will be run in the order you declare them in that file.

Anyway, if you are writing hooks that are affecting each other, you should maybe reconsider that. Hooks should be independent and if possible. If you want a hook to run after the other want, maybe you should just put them together in the same function :smile

I hope that helps.

I close this issue because i think the problem is solved 😄
